# ----------------
# GitHub Actions: Linter
# My created new GitHub Action)))
#-----------------

name: GitHub-Actions-linter


on: 
  push:
    branches: master
  
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hallee/eslint-action@master
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
