# ----------------
# GitHub Actions: Linter
# My created new GitHub Action)))
#-----------------

name: GitHub-Actions-linter


on: 
  push:
    branches: master
  
jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Make Lint
      run: make lint

