# ----------------
# GitHub Actions: Linter
# My created new GitHub Action)))
#-----------------

name: GitHub-Actions-linter


on: 
  push:
    branches: master
  
jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Clone my repo
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install Depend-s
      run: npm install
      
      
    - name: install Linter
      run: npm install eslint --save-dev
      
    - name: Run Linter
      run: npx lint .

