# ----------------
# GitHub Actions: Linter
# My created new GitHub Action)))
#-----------------

name: GitHub-Actions-linter


on: 
  push:
    branches: master
  
jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Clone my repo
      uses: actions/checkout@v1
      
    - name: Run Lint from Makefile
      run: make lint

